name = "MundorumFabrica"
uuid = "df92cde3-a597-4395-831b-5473045923f4"
authors = ["Devin Rockwell <zimlit2010@gmail.com>"]
version = "1.0.0-DEV"

[compat]
julia = "1.9"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
